export const CONSTANTS = {
    WINDOW_WIDTH: 1008,
    WINDOW_HEIGHT: 768,
    TERRAIN_TILE_SIZE: 48,
    PLAYER_TILE_SIZE: 32,
    BG_MUSIC_AUDIO: 'bgMusic',
    BG_MUSIC_TEXTURE_PATH: 'Audio/GameMusic.mp3',
    BUTTON_AUDIO: 'button',
    BUTTON_AUDIO_TEXTURE_PATH: 'Audio/button.mp3',
    DEBRIS_HIT_AUDIO: 'debrisHit',
    DEBRIS_HIT_AUDIO_TEXTURE_PATH: 'Audio/debrisHit.mp3',
    ENEMY_HIT_AUDIO: 'enemyHit',
    ENEMY_HIT_AUDIO_TEXTURE_PATH: 'Audio/enemyHit.mp3',
    PLAYER_JUMP_AUDIO: 'playerJump',
    PLAYER_JUMP_AUDIO_TEXTURE_PATH: 'Audio/playerJump.mp3',
    PLAYER_RUN_AUDIO: 'run',
    PLAYER_RUN_AUDIO_TEXTURE_PATH: 'Audio/run.mp3',
    GAME_OVER_AUDIO: 'gmOver',
    GAME_OVER_AUDIO_TEXTURE_PATH: 'Audio/gameOver.mp3',
    PLATFORM: 'platform',
    PLATFORM_TEXTURE_PATH: 'Platforms/Terrain.png',
    DEBRIS: 'debris' ,
    DEBRIS_TEXTURE_PATH: 'Platforms/Rock Head/Idle.png',
    ENEMY: 'enemy',
    ENEMY_TEXTURE_PATH: 'Platforms/Saw/On (38x38).png',
    PLAYER_IDLE: 'playerIdle',
    PLAYER_RUN: 'playerRun',
    PLAYER_JUMP: 'playerJump',
    PLAYER_FALL: 'playerFall',
    PLAYER_IDLE_TEXTURE_PATH: 'Character/Ninja_Frog/Idle.png',
    PLAYER_RUN_TEXTURE_PATH: 'Character/Ninja_Frog/Run.png',
    PLAYER_JUMP_TEXTURE_PATH: 'Character/Ninja_Frog/Jump.png',
    PLAYER_FALL_TEXTURE_PATH: 'Character/Ninja_Frog/Fall.png',
}