export const CONSTANTS = {
    WINDOW_WIDTH: 1008,
    WINDOW_HEIGHT: 768,
    TERRAIN_TILE_SIZE: 48,
    PLAYER_TILE_SIZE: 32,
    PLATFORM: 'platform',
    PLATFORM_TEXTURE_PATH: 'Platforms/Terrain.png',
    DEBRIS: 'debris' ,
    DEBRIS_TEXTURE_PATH: 'Platforms/Rock Head/Idle.png',
    ENEMY: 'enemy',
    ENEMY_TEXTURE_PATH: 'Platforms/Saw/On (38x38).png',
    PLAYER_IDLE: 'playerIdle',
    PLAYER_RUN: 'playerRun',
    PLAYER_JUMP: 'playerJump',
    PLAYER_FALL: 'playerFall',
    PLAYER_IDLE_TEXTURE_PATH: 'Character/Ninja_Frog/Idle.png',
    PLAYER_RUN_TEXTURE_PATH: 'Character/Ninja_Frog/Run.png',
    PLAYER_JUMP_TEXTURE_PATH: 'Character/Ninja_Frog/Jump.png',
    PLAYER_FALL_TEXTURE_PATH: 'Character/Ninja_Frog/Fall.png',
}